---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cross-seed.fullname" . }}-api-key
  labels:
    {{- include "cross-seed.labels" . | nindent 4 }}
data:
  API_KEY: {{ randAlphaNum 32 | b64enc }}